# Generated by Django 3.0.8 on 2020-07-01 20:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'region',
                'verbose_name_plural': 'regions',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, verbose_name='code')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.Region',
                                             verbose_name='region')),
            ],
            options={
                'verbose_name': 'county',
                'verbose_name_plural': 'counties',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_insee', models.CharField(max_length=50, verbose_name='code insee')),
                ('code_postal', models.CharField(max_length=50, verbose_name='code postal')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('population', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='population')),
                ('area', models.DecimalField(decimal_places=1, max_digits=8, verbose_name='area')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.County',
                                             verbose_name='county')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
    ]
